name: Test markdown

on:
  workflow_dispatch:

jobs:
  test-md:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write  # Required for attestation
        id-token: write      # Added for OIDC token access
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Test Markdown
        run: |
          cat .github/workflows/mymd.md >> $GITHUB_STEP_SUMMARY
