name: Test markdown

on:
  workflow_dispatch:

jobs:
  promote-to-production:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write  # Required for attestation
        id-token: write      # Added for OIDC token access
    
    steps:
      - name: Test Markdown
        run: |
          cat mymd.md >> $GITHUB_STEP_SUMMARY
