name: Verify Attestation
on:
    workflow_dispatch: 

env:
  REGISTRY: 192.168.50.113:8082
  IMAGE_NAME: my-docker-local/sigs
  GH_TOKEN: ${{ github.token }}

jobs:
    verify:
        runs-on: self-hosted
        permissions:
          contents: read
          packages: write
          attestations: write  # Required for attestation
          id-token: write      # Added for OIDC token access
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: admin
                password: password

            - name: GH Attestation
              run: |
                gh attestation verify oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main -R alenon/sigs
